services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: fashion
      MYSQL_USER: fashion
      MYSQL_PASSWORD: strongandsecurepassword
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/init.sql

  python-app:
    build: .
    container_name: python-frontend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: fashion
      DB_PASSWORD: strongandsecurepassword
      DB_NAME: fashion
    volumes:
      - .:/app
