services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: fashion
      MYSQL_USER: fashion
      MYSQL_PASSWORD: strongandsecurepassword
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/init.sql

  python-app:
    build: .
    container_name: python-frontend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: fashion
      DB_PASSWORD: strongandsecurepassword
      DB_NAME: fashion
      LYKDAT_API_KEY: ${LYKDAT_API_KEY}
      WEATHER_KEY: ${WEATHER_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GOOGLE_IMAGES_API_KEY: ${GOOGLE_IMAGES_API_KEY}
      GOOGLE_IMAGES_PROJ_CX: ${GOOGLE_IMAGES_PROJ_CX}
    volumes:
      - .:/app