name: Running Code Coverage
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.14
    - name: Install dependencies
      run: |
        pip install pytest-cov
    - name: Run the tests
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
      run: |
          pip install -r requirements.txt
          pytest --cov=tests
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
